### PR TITLE
Add New Africa to template.properties & others

### PR DESCRIPTION
**Pull request by heipizhu4**
1. Add New Africa to the template as well as Marieners' cities #33 Thanks @HaneulCheong for reminding me.
2. Put the changes into SImpified_Chinese.properties

### CODE REVIEW

**Review by SpacedOutChicken — COMMENTED** [review]
Is it necessary to translate New Afrika's city names? I pulled all of them directly from the base game, and I assumed that they would be automatically translated. Is that not happening?

**Comment by HaneulCheong** [comment]
> Is it necessary to translate New Afrika's city names? I pulled all of them directly from the base game, and I assumed that they would be automatically translated. Is that not happening?

This is something I wanted to mention about in the near future.

In my honest opinion it's painful and time-consuming to check every key and make sure whether it is included in the base game or not. One cannot memorize all the keys and even if one somehow manage to do it things change very quickly since both the base game and this mod is very active. Not to mention the possibility of the same keys in the base game and the mod meaning two very different things when considering context.

Perhaps we can include all the keys but comment it out. Like this:

```properties
# . . .

Unique Key 1 = Unique Key 1 Translation
# Base Game Key
Unique Key 2 = Unique Key 2 Translation

# . . .
```

I don't think out right removing it from this mod's template is a good idea in the long run.

**Comment by HaneulCheong** [comment]
Better yet, translators may reinclude the key on demand by simply uncommenting the line by using the method above. At least I translated `Rationalism` differently versus the base game.

**Comment by heipizhu4** [comment]
For now, will it be good to write something like
`Gao =
Tombouctu =
Jenne =
Taghaza =
Tondibi =
Kumbi Saleh =
Kukia =
(omitted)
Jimma =
Jijiga =
Dessie =
Debre Berhan =
Pi-Ramesses =
Giza =
Byblos =
#From Gao to Byblos is translated in the base game. Copy and retranslat if you translate them in a diffrent way.`

**Comment by heipizhu4** [comment]
Wait，I haven't made that commit yet:(

**Comment by heipizhu4** [comment]
Anyway, I'll put in my next pull

**Comment by heipizhu4** [comment]
Anyway, I'll put in my next pull

**Pull request merged**
