### PR TITLE
Translation converts from Traditional Chinese

### PR DESCRIPTION
**Pull request by heipizhu4**
Is it legal or should I get @GeneralWadaling 's permission?

### CODE REVIEW

**Comment by GeneralWadaling** [comment]
Just use it if you would like to :)

**Comment by heipizhu4** [comment]
@SpacedOutChicken I wonder when this PR will be merged……

**Comment by GeneralWadaling** [comment]
I have no idea lol
Also I think Deciv has transferred ownership again

**Comment by SpacedOutChicken** [comment]
@GeneralWadaling @heipizhu4 Are you both in agreement that this translation is legit? I am ready to approve it if it is.

**Comment by heipizhu4** [comment]
> @GeneralWadaling @heipizhu4 Are you both in agreement that this translation is legit? I am ready to approve it if it is.

I think it is legit as the only 2 contibutors in `Traditional_Chinese.properties` are you and @GeneralWadaling  . Since we've got his agreement in an early comment in this PR 28days ago. I think it's all right.

**Pull request merged**
